In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('AAPL.csv')
schema_df = pd.read_csv('AAPl.csv')

In [3]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [4]:
df.head()

Date        Open        High         Low       Close   Adj Close  \
0  2019-02-11  171.050003  171.210007  169.250000  169.429993  167.240967   
1  2019-02-12  170.100006  171.000000  169.699997  170.889999  168.682114   
2  2019-02-13  171.389999  172.479996  169.919998  170.179993  167.981277   
3  2019-02-14  169.710007  171.259995  169.380005  170.800003  168.593292   
4  2019-02-15  171.250000  171.699997  169.750000  170.419998  168.218201   

     Volume  
0  20993400  
1  22283500  
2  22490200  
3  21835700  
4  24626800

In [5]:
schema_df

Date        Open        High         Low       Close   Adj Close  \
0    2019-02-11  171.050003  171.210007  169.250000  169.429993  167.240967   
1    2019-02-12  170.100006  171.000000  169.699997  170.889999  168.682114   
2    2019-02-13  171.389999  172.479996  169.919998  170.179993  167.981277   
3    2019-02-14  169.710007  171.259995  169.380005  170.800003  168.593292   
4    2019-02-15  171.250000  171.699997  169.750000  170.419998  168.218201   
5    2019-02-19  169.710007  171.440002  169.490005  170.929993  168.721588   
6    2019-02-20  171.190002  173.320007  170.990005  172.029999  169.807388   
7    2019-02-21  171.800003  172.369995  170.300003  171.059998  168.849930   
8    2019-02-22  171.580002  173.000000  171.380005  172.970001  170.735229   
9    2019-02-25  174.160004  175.869995  173.949997  174.229996  171.978958   
10   2019-02-26  173.710007  175.300003  173.169998  174.330002  172.077667   
11   2019-02-27  173.210007  175.000000  172.729996  174.869995  172.610687   
12   2019-02-28  174.320007  174.910004  172.919998  173.149994  170.912918   
13   2019-03-01  174.279999  175.149994  172.889999  174.970001  172.709381   
14   2019-03-04  175.690002  177.750000  173.970001  175.850006  173.578033   
15   2019-03-05  175.940002  176.000000  174.539993  175.529999  173.262161   
16   2019-03-06  174.669998  175.490005  173.940002  174.520004  172.265228   
17   2019-03-07  173.869995  174.440002  172.020004  172.500000  170.271317   
18   2019-03-08  170.320007  173.070007  169.500000  172.910004  170.676025   
19   2019-03-11  175.490005  179.119995  175.350006  178.899994  176.588608   
20   2019-03-12  180.000000  182.669998  179.369995  180.910004  178.572662   
21   2019-03-13  182.250000  183.300003  180.919998  181.710007  179.362320   
22   2019-03-14  183.899994  184.100006  182.559998  183.729996  181.356216   
23   2019-03-15  184.850006  187.330002  183.740005  186.119995  183.715332   
24   2019-03-18  185.800003  188.389999  185.789993  188.020004  185.590805   
25   2019-03-19  188.350006  188.990005  185.919998  186.529999  184.120056   
26   2019-03-20  186.229996  189.490005  184.729996  188.160004  185.728989   
27   2019-03-21  190.020004  196.330002  189.809998  195.089996  192.569427   
28   2019-03-22  195.339996  197.690002  190.779999  191.050003  188.581650   
29   2019-03-25  191.509995  191.979996  186.600006  188.740005  186.301483   
30   2019-03-26  191.660004  192.880005  184.580002  186.789993  184.376678   
31   2019-03-27  188.750000  189.759995  186.550003  188.470001  186.034973   
32   2019-03-28  188.949997  189.559998  187.529999  188.720001  186.281738   
33   2019-03-29  189.830002  190.080002  188.539993  189.949997  187.495865   
34   2019-04-01  191.639999  191.679993  188.380005  191.240005  188.769211   
35   2019-04-02  191.089996  194.460007  191.050003  194.020004  191.513290   
36   2019-04-03  193.250000  196.500000  193.149994  195.350006  192.826111   
37   2019-04-04  194.789993  196.369995  193.139999  195.690002  193.161682   
38   2019-04-05  196.449997  197.100006  195.929993  197.000000  194.454758   
39   2019-04-08  196.419998  200.229996  196.339996  200.100006  197.514709   
40   2019-04-09  200.320007  202.850006  199.229996  199.500000  196.922470   
41   2019-04-10  198.679993  200.740005  198.179993  200.619995  198.027985   
..          ...         ...         ...         ...         ...         ...   
209  2019-12-09  270.000000  270.799988  264.910004  266.920013  266.288025   
210  2019-12-10  268.600006  270.070007  265.859985  268.480011  267.844330   
211  2019-12-11  268.809998  271.100006  268.500000  270.769989  270.128906   
212  2019-12-12  267.779999  272.559998  267.320007  271.459991  270.817261   
213  2019-12-13  271.459991  275.299988  270.929993  275.149994  274.498535   
214  2019-12-16  277.000000  280.790009  276.980011  279.859985  279.197357   
215  2019-12-17  279.570007  281.769989  278.799988  280.4100

In [6]:
df.shape

(251, 7)

# Pandas series

In [3]:
#creatoing an empty series
import pandas as pd  
x = pd.Series()  
print (x)  

Series([], dtype: float64)


In [4]:
##creating series from arrays
import pandas as pd  
import numpy as np  
info = np.array(['P','a','n','d','a','s'])  
a = pd.Series(info)  
print(a)  

0    P
1    a
2    n
3    d
4    a
5    s
dtype: object


In [5]:
#import the pandas library (series from dictionary)  
import pandas as pd  
import numpy as np  
info = {'x' : 0., 'y' : 1., 'z' : 2.}  
a = pd.Series(info)  
print (a)  

x    0.0
y    1.0
z    2.0
dtype: float64


In [7]:
##creating series usinmg scalar
#import pandas library   
import pandas as pd  
import numpy as np  
x = pd.Series(4, index=[0, 1, 2, 3])  
print (x) 


0    4
1    4
2    4
3    4
dtype: int64


In [8]:
## Accesing data from series position
import pandas as pd  
x = pd.Series([1,2,3],index = ['a','b','c'])  
#retrieve the first element  
print (x[0])  

1


In [9]:
# Retrieving Index array and data array of a series object
import numpy as np   
import pandas as pd   
x=pd.Series(data=[2,4,6,8])   
y=pd.Series(data=[11.2,18.6,22.5], index=['a','b','c'])   
print(x.index)   
print(x.values)   
print(y.index)   
print(y.values) 

RangeIndex(start=0, stop=4, step=1)
[2 4 6 8]
Index(['a', 'b', 'c'], dtype='object')
[11.2 18.6 22.5]


In [10]:
##Retrieving Types (dtype) and Size of Type (itemsize)
import numpy as np   
import pandas as pd   
a=pd.Series(data=[1,2,3,4])   
b=pd.Series(data=[4.9,8.2,5.6],   
index=['x','y','z'])   
print(a.dtype)   
print(a.itemsize)    
print(b.dtype)   
print(b.itemsize)  

int64
8
float64
8


C:\Users\New life\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  
C:\Users\New life\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  # Remove the CWD from sys.path while we load stuff.


In [11]:
##retrieving shape
import numpy as np   
import pandas as pd   
a=pd.Series(data=[1,2,3,4])   
b=pd.Series(data=[4.9,8.2,5.6],index=['x','y','z'])   
print(a.shape)   
print(b.shape) 

(4,)
(3,)


In [12]:
##Retrieving Dimension, Size and Number of bytes:
import numpy as np   
import pandas as pd   
a=pd.Series(data=[1,2,3,4])   
b=pd.Series(data=[4.9,8.2,5.6],  
index=['x','y','z'])   
print(a.ndim, b.ndim)   
print(a.size, b.size)   
print(a.nbytes, b.nbytes)  

1 1
4 3
32 24


In [13]:
##Checking Emptiness and Presence of NaNs
import numpy as np   
import pandas as pd   
a=pd.Series(data=[1,2,3,np.NaN])   
b=pd.Series(data=[4.9,8.2,5.6],index=['x','y','z'])   
c=pd.Series()   
print(a.empty,b.empty,c.empty)   
print(a.hasnans,b.hasnans,c.hasnans)   
print(len(a),len(b))   
print(a.count( ),b.count( ))  

False False True
True False False
4 3
3 3


In [14]:
#series.map function
import pandas as pd  
import numpy as np  
a = pd.Series(['Java', 'C', 'C++', np.nan])  
a.map({'Java': 'Core'})  

0    Core
1     NaN
2     NaN
3     NaN
dtype: object

In [15]:
import pandas as pd  
import numpy as np  
a = pd.Series(['Java', 'C', 'C++', np.nan])  
a.map({'Java': 'Core'})  
a.map('I like {}'.format, na_action='ignore')  

0    I like Java
1       I like C
2     I like C++
3            NaN
dtype: object

In [16]:
## Pandas import pandas as pd  
# calculate standard deviation  
import pandas as pd  
# calculate standard deviation  
import numpy as np   
print(np.std([4,7,2,1,6,3]))  
print(np.std([6,9,15,2,-17,15,4]))  


2.1147629234082532
10.077252622027656


In [17]:
import pandas as pd  
import numpy as np  
   
#Create a DataFrame  
info = {  
    'Name':['Parker','Smith','John','William'],  
   'sub1_Marks':[52,38,42,37],  
   'sub2_Marks':[41,35,29,36]}   
data = pd.DataFrame(info)  
data  
# standard deviation of the dataframe  
data.std()

sub1_Marks    6.849574
sub2_Marks    4.924429
dtype: float64

In [18]:
##Pandas Series.to_frame()(returns the representation of series)
s = pd.Series(["a", "b", "c"],  
name="vals")  
s.to_frame()  


vals
0    a
1    b
2    c

In [20]:
import pandas as pd   
import matplotlib.pyplot as plt     
emp = ['Parker', 'John', 'Smith', 'William']   
id = [102, 107, 109, 114]     
emp_series = pd.Series(emp)   
id_series = pd.Series(id)     
frame = { 'Emp': emp_series, 'ID': id_series }   
result = pd.DataFrame(frame)     
print(result) 

       Emp   ID
0   Parker  102
1     John  107
2    Smith  109
3  William  114


In [22]:
##Pandas Series.unique()
#Returns:
##(This method returns a numpy.ndarray or ExtensionArray object and can be:

##index: Returns when user passes index as an input.
##Categorical: Returns when user passes a Categorical dtype as an input.
#3ndarray: Returns when user passes a ndarray/Series as an input.)
import pandas as pd  
pd.unique(pd.Series([2, 1, 3, 3]))  
pd.unique(pd.Series([pd.Timestamp('20160101'),  
pd.Timestamp('20160101')]))  

array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [23]:
import pandas as pd  
import numpy as np  
pd.unique(pd.Index([pd.Timestamp('20160101', tz='US/Eastern'),  
pd.Timestamp('20160101', tz='US/Eastern')]))  

DatetimeIndex(['2016-01-01 00:00:00-05:00'], dtype='datetime64[ns, US/Eastern]', freq=None)

In [24]:
##Pandas Series.value_counts()
##returns the counted series
import pandas as pd  
import numpy as np  
index = pd.Index([2, 1, 1, np.nan, 3])  
index.value_counts()  

1.0    2
3.0    1
2.0    1
dtype: int64

In [25]:
import pandas as pd  
import numpy as np  
index = pd.Index([2, 1, 1, np.nan, 3])  
a = pd.Series([2, 1, 1, np.nan, 3])  
a.value_counts(normalize=True)  

1.0    0.50
3.0    0.25
2.0    0.25
dtype: float64

In [26]:
import pandas as pd  
index = pd.Index([1, 3, 2, 2, 1, np.nan])  
index.value_counts()  
a = pd.Series([1, 3, 2, 2, 1, np.nan])  
a.value_counts(bins=2)  

(0.997, 2.0]    4
(2.0, 3.0]      1
dtype: int64

In [27]:
import pandas as pd  
index = pd.Index([1, 3, 2, 2, 1, np.nan])  
index.value_counts()  
a = pd.Series([1, 3, 2, 2, 1, np.nan])  
a.value_counts(dropna=False)  

2.0    2
1.0    2
NaN    1
3.0    1
dtype: int64

# Pandas dataframe

In [28]:
##creating empty datasfame
# importing the pandas library  
import pandas as pd  
df = pd.DataFrame()  
print (df)  

Empty DataFrame
Columns: []
Index: []


In [29]:
#using list
# importing the pandas library  
import pandas as pd  
# a list of strings  
x = ['Python', 'Pandas']  
  
# Calling DataFrame constructor on list  
df = pd.DataFrame(x)  
print(df) 

        0
0  Python
1  Pandas


In [30]:
#Create a DataFrame from Dict of ndarrays/ Lists
# importing the pandas library  
import pandas as pd  
info = {'ID' :[101, 102, 103],'Department' :['B.Sc','B.Tech','M.Tech',]}  
df = pd.DataFrame(info)  
print (df)  

    ID Department
0  101       B.Sc
1  102     B.Tech
2  103     M.Tech


In [31]:
#create dataframer of dict of series
# importing the pandas library  
import pandas as pd  
  
info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f']),  
   'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])}  
  
d1 = pd.DataFrame(info)  
print (d1) 

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  4.0    4
e  5.0    5
f  6.0    6
g  NaN    7
h  NaN    8


In [32]:
#column selection
# importing the pandas library  
import pandas as pd  
  
info = {'one' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f']),  
   'two' : pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])}  
  
d1 = pd.DataFrame(info)  
print (d1 ['one'])  

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    NaN
h    NaN
Name: one, dtype: float64


In [33]:
##column addition
# importing the pandas library  
import pandas as pd  
  
info = {'one' : pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']),  
   'two' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f'])}  
  
df = pd.DataFrame(info)  
  
# Add a new column to an existing DataFrame object   
  
print ("Add new column by passing series")  
df['three']=pd.Series([20,40,60],index=['a','b','c'])  
print (df)  
  
print ("Add new column using existing DataFrame columns")  
df['four']=df['one']+df['three']  
  
print (df)  

Add new column by passing series
   one  two  three
a  1.0    1   20.0
b  2.0    2   40.0
c  3.0    3   60.0
d  4.0    4    NaN
e  5.0    5    NaN
f  NaN    6    NaN
Add new column using existing DataFrame columns
   one  two  three  four
a  1.0    1   20.0  21.0
b  2.0    2   40.0  42.0
c  3.0    3   60.0  63.0
d  4.0    4    NaN   NaN
e  5.0    5    NaN   NaN
f  NaN    6    NaN   NaN


In [34]:
##column deletion
# importing the pandas library  
import pandas as pd  
  
info = {'one' : pd.Series([1, 2], index= ['a', 'b']),   
   'two' : pd.Series([1, 2, 3], index=['a', 'b', 'c'])}  
     
df = pd.DataFrame(info)  
print ("The DataFrame:")  
print (df)  
  
# using del function  
print ("Delete the first column:")  
del df['one']  
print (df)  
# using pop function  
print ("Delete the another column:")  
df.pop('two')  
print (df)  

The DataFrame:
   one  two
a  1.0    1
b  2.0    2
c  NaN    3
Delete the first column:
   two
a    1
b    2
c    3
Delete the another column:
Empty DataFrame
Columns: []
Index: [a, b, c]


In [35]:
##row serlection
# importing the pandas library  
import pandas as pd  
  
info = {'one' : pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']),   
   'two' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f'])}  
  
df = pd.DataFrame(info)  
print (df.loc['b'])  

one    2.0
two    2.0
Name: b, dtype: float64


In [36]:
#selection by integer location
# importing the pandas library  
import pandas as pd  
info = {'one' : pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']),  
   'two' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f'])}  
df = pd.DataFrame(info)  
print (df.iloc[3])  

one    4.0
two    4.0
Name: d, dtype: float64


In [37]:
##Slice Rows

#3It is another method to select multiple rows using ':' operator.
import pandas as pd  
info = {'one' : pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']),   
   'two' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f'])}  
df = pd.DataFrame(info)  
print (df[2:5])  

   one  two
c  3.0    3
d  4.0    4
e  5.0    5


In [38]:
##addition of rows
import pandas as pd  
d = pd.DataFrame([[7, 8], [9, 10]], columns = ['x','y'])  
d2 = pd.DataFrame([[11, 12], [13, 14]], columns = ['x','y'])  
d = d.append(d2)  
print (d)  

    x   y
0   7   8
1   9  10
0  11  12
1  13  14


In [44]:
##deletion of rows
# importing the pandas library  
import pandas as pd  
  
a_info = pd.DataFrame([[4, 5], [6, 7]], columns = ['x','y'])  
b_info = pd.DataFrame([[8, 9], [10, 11]], columns = ['x','y'])  
  
a_info = a_info.append(b_info)  
  
# Drop rows with label 0  
a_info = a_info.drop(0)

# Pandas operation

In [47]:
import pandas as pd  
aa = pd.read_csv("AAPL.csv")  
aa.head()

Date        Open        High         Low       Close   Adj Close  \
0  2019-02-11  171.050003  171.210007  169.250000  169.429993  167.240967   
1  2019-02-12  170.100006  171.000000  169.699997  170.889999  168.682114   
2  2019-02-13  171.389999  172.479996  169.919998  170.179993  167.981277   
3  2019-02-14  169.710007  171.259995  169.380005  170.800003  168.593292   
4  2019-02-15  171.250000  171.699997  169.750000  170.419998  168.218201   

     Volume  
0  20993400  
1  22283500  
2  22490200  
3  21835700  
4  24626800

In [49]:
#adding new column
import pandas as pd  
aa = pd.read_csv("AAPL.csv")  
aa["Profit"] = "24"  
aa.head()  

Date        Open        High         Low       Close   Adj Close  \
0  2019-02-11  171.050003  171.210007  169.250000  169.429993  167.240967   
1  2019-02-12  170.100006  171.000000  169.699997  170.889999  168.682114   
2  2019-02-13  171.389999  172.479996  169.919998  170.179993  167.981277   
3  2019-02-14  169.710007  171.259995  169.380005  170.800003  168.593292   
4  2019-02-15  171.250000  171.699997  169.750000  170.419998  168.218201   

     Volume Profit  
0  20993400     24  
1  22283500     24  
2  22490200     24  
3  21835700     24  
4  24626800     24

In [53]:
##adding new column department
import pandas as pd  
aa = pd.read_csv("AAPL.csv")  
aa.insert(2, column = "Department", value = "company")  
aa.head()


Date        Open Department        High         Low       Close  \
0  2019-02-11  171.050003    company  171.210007  169.250000  169.429993   
1  2019-02-12  170.100006    company  171.000000  169.699997  170.889999   
2  2019-02-13  171.389999    company  172.479996  169.919998  170.179993   
3  2019-02-14  169.710007    company  171.259995  169.380005  170.800003   
4  2019-02-15  171.250000    company  171.699997  169.750000  170.419998   

    Adj Close    Volume  
0  167.240967  20993400  
1  168.682114  22283500  
2  167.981277  22490200  
3  168.593292  21835700  
4  168.218201  24626800

In [54]:
##dataframe to numpy array
import pandas as pd  
pd.DataFrame({"P": [2, 3], "Q": [4, 5]}).to_numpy()  
info = pd.DataFrame({"P": [2, 3], "Q": [4.0, 5.8]})  
info.to_numpy()  
info['R'] = pd.date_range('2000', periods=2)  
info.to_numpy()  

array([[2, 4.0, Timestamp('2000-01-01 00:00:00')],
       [3, 5.8, Timestamp('2000-01-02 00:00:00')]], dtype=object)

In [55]:
import pandas as pd  
#initializing the dataframe  
info = pd.DataFrame([[17, 62, 35],[25, 36, 54],[42, 20, 15],[48, 62, 76]],  
columns=['x', 'y', 'z'])  
print('DataFrame\n----------\n', info)  
#convert the dataframe to a numpy array  
arr = info.to_numpy()  
print('\nNumpy Array\n----------\n', arr)  

DataFrame
----------
     x   y   z
0  17  62  35
1  25  36  54
2  42  20  15
3  48  62  76

Numpy Array
----------
 [[17 62 35]
 [25 36 54]
 [42 20 15]
 [48 62 76]]


In [56]:
##dataframe to csv
import pandas as pd  
data = {'Name': ['Smith', 'Parker'], 'ID': [101, 102], 'Language': ['Python', 'JavaScript']}  
info = pd.DataFrame(data)  
print('DataFrame Values:\n', info)  
# default CSV  
csv_data = info.to_csv()  
print('\nCSV String Values:\n', csv_data)  


DataFrame Values:
      Name   ID    Language
0   Smith  101      Python
1  Parker  102  JavaScript

CSV String Values:
 ,Name,ID,Language
0,Smith,101,Python
1,Parker,102,JavaScript



In [59]:
###reading from csv
import pandas  
df = pandas.read_csv('AAPL.csv')  
print(df)

           Date        Open        High         Low       Close   Adj Close  \
0    2019-02-11  171.050003  171.210007  169.250000  169.429993  167.240967   
1    2019-02-12  170.100006  171.000000  169.699997  170.889999  168.682114   
2    2019-02-13  171.389999  172.479996  169.919998  170.179993  167.981277   
3    2019-02-14  169.710007  171.259995  169.380005  170.800003  168.593292   
4    2019-02-15  171.250000  171.699997  169.750000  170.419998  168.218201   
5    2019-02-19  169.710007  171.440002  169.490005  170.929993  168.721588   
6    2019-02-20  171.190002  173.320007  170.990005  172.029999  169.807388   
7    2019-02-21  171.800003  172.369995  170.300003  171.059998  168.849930   
8    2019-02-22  171.580002  173.000000  171.380005  172.970001  170.735229   
9    2019-02-25  174.160004  175.869995  173.949997  174.229996  171.978958   
10   2019-02-26  173.710007  175.300003  173.169998  174.330002  172.077667   
11   2019-02-27  173.210007  175.000000  172.729996 

# Pandas data operation

In [60]:
##data processing with multiple index
import pandas as pd  
info = pd.Series([11, 14, 17, 24, 19, 32, 34, 27],  
index = [['x', 'x', 'x', 'x', 'y', 'y', 'y', 'y'],  
['obj1', 'obj2', 'obj3', 'obj4', 'obj1', 'obj2', 'obj3', 'obj4']])  
data

{'Name': ['Smith', 'Parker'],
 'ID': [101, NaT],
 'Language': [NaT, 'JavaScript']}

In [66]:
import pandas as pd  
aa = pd.read_csv("AAPL.csv")  
aa.head()  

Date        Open        High         Low       Close   Adj Close  \
0  2019-02-11  171.050003  171.210007  169.250000  169.429993  167.240967   
1  2019-02-12  170.100006  171.000000  169.699997  170.889999  168.682114   
2  2019-02-13  171.389999  172.479996  169.919998  170.179993  167.981277   
3  2019-02-14  169.710007  171.259995  169.380005  170.800003  168.593292   
4  2019-02-15  171.250000  171.699997  169.750000  170.419998  168.218201   

     Volume  
0  20993400  
1  22283500  
2  22490200  
3  21835700  
4  24626800

In [67]:
# importing pandas module   
import pandas as pd    
# making data frame from csv file   
info = pd.read_csv("AAPL.csv")     
# making a copy of old data frame   
copy = pd.read_csv("AAPL.csv")   
    
# creating value with all null values in new data frame   
copy["Null Column"]= None  
    
# checking if column is inserted properly    
print(info.columns.values, "\n", copy.columns.values)   
    
# comparing values before dropping null column   
print("\nColumn number before dropping Null column\n",   
       len(info.dtypes), len(copy.dtypes))   
    
# dropping column with all null values   
copy.dropna(axis = 1, how ='all', inplace = True)   
    
# comparing values after dropping null column   
print("\nColumn number after dropping Null column\n",   
      len(info.dtypes), len(info.dtypes))    

['Date' 'Open' 'High' 'Low' 'Close' 'Adj Close' 'Volume'] 
 ['Date' 'Open' 'High' 'Low' 'Close' 'Adj Close' 'Volume' 'Null Column']

Column number before dropping Null column
 7 8

Column number after dropping Null column
 7 7


In [68]:
#fllna 
import pandas as pd  
# Create a dataframe  
info = pd.DataFrame(data={'x':[10,20,30,40,50,None]})  
print(info)  
# Fill null value to dataframe using 'inplace'  
info.fillna(value=0, inplace=True)  
print(info) 

      x
0  10.0
1  20.0
2  30.0
3  40.0
4  50.0
5   NaN
      x
0  10.0
1  20.0
2  30.0
3  40.0
4  50.0
5   0.0


In [69]:
import pandas as pd  
# Create a dataframe  
info = pd.DataFrame([[np.nan,np.nan, 20, 0],  
[1, np.nan, 4, 1],  
[np.nan, np.nan, np.nan, 5],  
[np.nan, 20, np.nan, 2]],  
columns=list('ABCD'))  
info

A     B     C  D
0  NaN   NaN  20.0  0
1  1.0   NaN   4.0  1
2  NaN   NaN   NaN  5
3  NaN  20.0   NaN  2

In [70]:
#3daataframe replace
import pandas as pd  
info = pd.DataFrame({'Language known': ['Python', 'Android', 'C', 'Android', 'Python', 'C++', 'C']},  
index=['Parker', 'Smith', 'John', 'William', 'Dean', 'Christina', 'Cornelia'])  
print(info)   
dictionary = {"Python": 1, "Android": 2, "C": 3, "Android": 4, "C++": 5}  
info1 = info.replace({"Language known": dictionary})  
print("\n\n")  
print(info1) 

          Language known
Parker            Python
Smith            Android
John                   C
William          Android
Dean              Python
Christina            C++
Cornelia               C



           Language known
Parker                  1
Smith                   4
John                    3
William                 4
Dean                    1
Christina               5
Cornelia                3


In [71]:
import pandas as pd  
info = pd.DataFrame({  
    'name':['Parker','Smith','John'],  
    'age':[27,34,31],  
    'city':['US','Belgium','London']  
})  
info.replace([29],38)  

name  age     city
0  Parker   27       US
1   Smith   34  Belgium
2    John   31   London